version: '3.8'

services:
  agentflow-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: agentflow:latest
    container_name: agentflow-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_WS_URL=${REACT_APP_WS_URL}
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - agentflow-logs:/var/log/nginx
    networks:
      - agentflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  agentflow-logs:
    driver: local

networks:
  agentflow-network:
    driver: bridge
