# Prometheus Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'unified-agent-system'
    environment: 'production'

scrape_configs:
  - job_name: 'unified-agent-system'
    static_configs:
      - targets: ['unified-agent-system:8000']
        labels:
          service: 'api'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'database'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'cache'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  []
