apiVersion: v1
kind: ConfigMap
metadata:
  name: ymera-config
  namespace: ymera
data:
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  ENABLE_DISTRIBUTED_TRACING: "true"
  ENABLE_METRICS_EXPORT: "true"
  ENABLE_HEALTH_CHECKS: "true"
  SERVICE_NAME: "ymera-agents"
  SERVICE_VERSION: "2.0.0"
  PROMETHEUS_ENABLED: "true"
  JAEGER_ENABLED: "true"
  JAEGER_AGENT_HOST: "jaeger-agent"
  JAEGER_AGENT_PORT: "6831"
