blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/meraalfai-oss/ymera-frontend-/tree/main/docs
    about: Read the documentation for guides and API references
  - name: 💬 Discussions
    url: https://github.com/meraalfai-oss/ymera-frontend-/discussions
    about: Ask questions and discuss with the community
  - name: 🔒 Security Issues
    url: https://github.com/meraalfai-oss/ymera-frontend-/security/advisories/new
    about: Report security vulnerabilities privately
