name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Check and Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Check for outdated dependencies
        id: outdated
        run: |
          npm outdated --json > outdated.json || true
          cat outdated.json
        continue-on-error: true
        
      - name: Run security audit
        id: audit
        run: |
          npm audit --json > audit.json || true
          cat audit.json
        continue-on-error: true
        
      - name: Update dependencies
        run: |
          npm update
          npm audit fix --force || true
          
      - name: Run tests
        run: |
          npm ci
          npm run test:coverage
        continue-on-error: true
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: Weekly dependency updates'
          body: |
            ## Dependency Updates
            
            This PR contains automated dependency updates.
            
            ### Outdated Packages
            ```json
            $(cat outdated.json)
            ```
            
            ### Security Audit
            ```json
            $(cat audit.json)
            ```
            
            Please review the changes and ensure all tests pass before merging.
          branch: automated-dependency-updates
          delete-branch: true
          labels: dependencies, automated
